tierperso_sylius_amazon_pay_start:
#    path: /start TODO add
    path: cart/
    methods: [GET]
    defaults:
        _controller: tierperso_sylius_amazon_pay_plugin.controller.action.amazon_pay_start

tierperso_sylius_amazon_pay_initialize:
    path: /initialize
    methods: [POST]
    defaults:
        _controller: tierperso_sylius_amazon_pay_plugin.controller.action.initialize

tierperso_sylius_amazon_pay_order_reference_create:
    path: /order-reference-create
    methods: [POST]
    defaults:
        _controller: tierperso_sylius_amazon_pay_plugin.controller.action.order_reference_create

tierperso_sylius_amazon_pay_address_select:
    path: /address-select
    methods: [POST]
    defaults:
        _controller: tierperso_sylius_amazon_pay_plugin.controller.action.address_select
