tierperso_sylius_amazon_pay_plugin_get_order_details:
    path: /order-details
    methods: [POST, GET]
    defaults:
        _controller: Tierperso\SyliusAmazonPayPlugin\Request\Api\AmazonPayOrderDetails::getAmazonOrderDetails
