tierperso_sylius_amazon_pay_plugin_get_order_details:
    path: /order-details
    methods: [POST, GET]
    defaults:
        _controller: Tierperso\SyliusAmazonPayPlugin\Api\AmazonPayOrderDetailsAction

tierperso_sylius_amazon_pay_plugin_get_order_detail:
    path: /order-detail
    methods: [POST, GET]
    defaults:
        _controller: Tierperso\SyliusAmazonPayPlugin\Api\AmazonPayOrderDetailAction
